controllers:
    resource: ../src/Controller
    type: annotation
    schemes:
        - HTTP
        - HTTPS

kernel:
    resource: '../src/Kernel.php'
    type: annotation
    schemes:
        - HTTP
        - HTTPS
